algo = input("Digite Algo:")
print("O tipo primitivo dessa digitação é", type(algo))
print("Só tem espaços?", algo.isspace())
print("Só tem numeros?", algo.isnumeric())
print("É alfabetico?", algo.isalpha)
print("É alpha numero?", algo.isalnum())
print("Está em maiusculas?", algo.isupper)
print("Está em minusculas?", algo.islower())
print("Está capitalizada?", algo.istitle())
